name: Build & Release CryptoZap

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        target: [cli, gui]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🛠 Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"

      - name: 🧪 Build CLI (cryptozap-cli)
        if: matrix.target == 'cli'
        run: |
          swift package clean
          swift build -c release --arch arm64 --arch x86_64 --product cryptozap-cli
          mkdir -p dist-cli
          cp .build/apple/Products/Release/cryptozap-cli dist-cli/
          cp -R .build/apple/Products/Release/CryptoEngine_CryptoEngine.bundle dist-cli/
          cp cryptozap-cli.1 dist-cli/
          gzip -f dist-cli/cryptozap-cli.1
          tar -czf cryptozap-cli-app.tar.gz -C dist-cli .

      - name: 🧪 Build GUI (.app)
        if: matrix.target == 'gui'
        run: |
          xcodebuild -scheme CryptoZap -configuration Release -archivePath CryptoZap.xcarchive archive
          xcodebuild -exportArchive -archivePath CryptoZap.xcarchive -exportPath dist-gui -exportOptionsPlist ExportOptions.plist

      - name: 📤 Upload CLI artifact
        if: matrix.target == 'cli'
        uses: actions/upload-artifact@v3
        with:
          name: cryptozap-cli-app
          path: cryptozap-cli-app.tar.gz

      - name: 📤 Upload GUI artifact
        if: matrix.target == 'gui'
        uses: actions/upload-artifact@v3
        with:
          name: CryptoZap.app
          path: dist-gui/CryptoZap.app

  release:
    needs: build
    runs-on: macos-13
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cryptozap-cli-app/cryptozap-cli-app.tar.gz
            dist/CryptoZap.app/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
